// https://w3c.github.io/webrtc-encoded-transform/#keyframerequestevent

[Exposed=DedicatedWorker]
interface KeyFrameRequestEvent : Event {
    [FIXME] constructor(DOMString type, optional DOMString rid);
    [FIXME] readonly attribute DOMString? rid;
};
