
// https://w3c.github.io/webrtc-pc/#rtcdatachannel

[Exposed=(Window,DedicatedWorker), Transferable]
interface RTCDataChannel : EventTarget {
    [FIXME] readonly attribute USVString label;
    [FIXME] readonly attribute boolean ordered;
    [FIXME] readonly attribute unsigned short? maxPacketLifeTime;
    [FIXME] readonly attribute unsigned short? maxRetransmits;
    [FIXME] readonly attribute USVString protocol;
    [FIXME] readonly attribute boolean negotiated;
    [FIXME] readonly attribute unsigned short? id;
    readonly attribute RTCDataChannelState readyState;
    readonly attribute unsigned long bufferedAmount;
    [EnforceRange] attribute unsigned long bufferedAmountLowThreshold;
    attribute EventHandler onopen;
    attribute EventHandler onbufferedamountlow;
    attribute EventHandler onerror;
    attribute EventHandler onclosing;
    attribute EventHandler onclose;
    [FIXME] undefined close();
    attribute EventHandler onmessage;
    [FIXME] attribute BinaryType binaryType;
    // FIXME: spec is 4 overloads (USVString / Blob / ArrayBuffer / ArrayBufferView). Codegen
    //        for typed overloads is fiddly; use the same union-arg shape as WebSocket.send.
    undefined send((USVString or Blob or BufferSource) data);
};

dictionary RTCDataChannelInit {
    boolean ordered = true;
    [EnforceRange] unsigned short maxPacketLifeTime;
    [EnforceRange] unsigned short maxRetransmits;
    USVString protocol = "";
    boolean negotiated = false;
    [EnforceRange] unsigned short id;
};

enum RTCDataChannelState { "connecting", "open", "closing", "closed" };
