// https://w3c.github.io/webrtc-pc/#rtcicecandidate-interface

[Exposed=Window]
interface RTCIceCandidate {
    constructor(optional RTCIceCandidateInit candidateInitDict = {});
    readonly attribute DOMString candidate;
    readonly attribute DOMString? sdpMid;
    readonly attribute unsigned short? sdpMLineIndex;
    readonly attribute DOMString? foundation;
    [FIXME] readonly attribute RTCIceComponent? component;
    [FIXME] readonly attribute unsigned long? priority;
    [FIXME] readonly attribute DOMString? address;
    [FIXME] readonly attribute RTCIceProtocol? protocol;
    [FIXME] readonly attribute unsigned short? port;
    [FIXME] readonly attribute RTCIceCandidateType? type;
    [FIXME] readonly attribute RTCIceTcpCandidateType? tcpType;
    [FIXME] readonly attribute DOMString? relatedAddress;
    [FIXME] readonly attribute unsigned short? relatedPort;
    readonly attribute DOMString? usernameFragment;
    readonly attribute RTCIceServerTransportProtocol? relayProtocol;
    [FIXME] readonly attribute DOMString? url;
    RTCIceCandidateInit toJSON();
};

dictionary RTCIceCandidateInit {
    DOMString candidate = "";
    DOMString? sdpMid = null;
    unsigned short? sdpMLineIndex = null;
    DOMString? usernameFragment = null;
};

enum RTCIceProtocol { "udp", "tcp" };
enum RTCIceTcpCandidateType { "active", "passive", "so" };
enum RTCIceCandidateType { "host", "srflx", "prflx", "relay" };
enum RTCIceServerTransportProtocol { "udp", "tcp", "tls" };
