/*
 * Copyright (c) 2026-present, the Ladybird developers.
 *
 * SPDX-License-Identifier: BSD-2-Clause
 */

#pragma once

#include <AK/Optional.h>
#include <AK/String.h>
#include <AK/Vector.h>
#include <LibWeb/Bindings/RTCRtpSender.h>

namespace Web::WebRTC {

// These dictionaries are generated by the bindings generator; use the generated types directly.
using Bindings::RTCRtcpParameters;
using Bindings::RTCRtpCapabilities;
using Bindings::RTCRtpCodec;
using Bindings::RTCRtpCodecParameters;
using Bindings::RTCRtpCodingParameters;
using Bindings::RTCRtpEncodingParameters;
using Bindings::RTCRtpHeaderExtensionCapability;
using Bindings::RTCRtpHeaderExtensionParameters;
using Bindings::RTCRtpParameters;
using Bindings::RTCRtpReceiveParameters;
using Bindings::RTCRtpSendParameters;
using Bindings::RTCSetParameterOptions;

}
