// https://w3c.github.io/webrtc-pc/#rtcsessiondescription-class

enum RTCSdpType {
    "offer",
    "pranswer",
    "answer",
    "rollback"
};

[Exposed=Window]
interface RTCSessionDescription {
    constructor(RTCSessionDescriptionInit descriptionInitDict);
    readonly attribute RTCSdpType type;
    readonly attribute DOMString sdp;
    [FIXME] RTCSessionDescriptionInit toJSON();
};

dictionary RTCSessionDescriptionInit {
    required RTCSdpType type;
    DOMString sdp = "";
};

dictionary RTCLocalSessionDescriptionInit {
    RTCSdpType type;
    DOMString sdp = "";
};
